### ISSUE TITLE
AttributeError: espidf object has no attribute 'spi_pre_cb_isr'

### ISSUE THREAD

**Issue by hn82123** [lvgl/lv_binding_micropython#102]
When we use the hybrid=false mode, with esp32 and ili9341,
the execution got an error:      

> File "ili9XXX.py", line 171, in disp_spi_init
AttributeError: 'module' object has no attribute 'spi_pre_cb_isr'

This error points to the code:
```
devcfg.pre_cb = esp.spi_pre_cb_isr
devcfg.post_cb = esp.spi_post_cb_isr
```

And I can't find the function registration in the generated module .C file

**Comment by amirgon** [comment]
Hi @hn82123 !
Thank you for reporting this.
It has been long time since I last tried the non-hybrid version. As you noticed, it is broken.
I'm fixing it now.
