### ISSUE TITLE
ili9488 + xpt2046 screen not responding to touch 

### ISSUE THREAD

**Issue by dukeduck1984** [lvgl/lv_binding_micropython#116]
This happens when ili9488 and xpt2046 share the same spi bus, the display works fine but the screen won't respond to touch.

The similar issue was aslo reported and discussed in [this repo](https://github.com/Bodmer/TFT_eSPI/issues/177).

The temporary solution is to disconnect the MISO of the display, but then the display somehow becomes 'slow' (which is based on my observation).  Pls see the forum discussion [here](https://forum.lvgl.io/t/screen-not-responding-to-touch/4364/9).

I was using MicroPython v1.13 + LVGL v.7.9, ESP32 Wrover module.

**Comment by embeddedt** [comment]
Closing, as this issue was resolved on the forum (and stale-bot is broken now).
