### ISSUE TITLE
Merge Micropython v1.14

### ISSUE THREAD

**Issue by amirgon** [lvgl/lv_binding_micropython#118]
https://github.com/micropython/micropython/releases/tag/v1.14

**Comment by embeddedt** [comment]
> support added for C++ user modules on unix, stm32 and esp32.

Is this something we'd want to look into?

**Comment by amirgon** [comment]
Only if for some reason we want to build C++ user modules.
Currently the binding generates C modules, so I don't think that would be useful for us at this point.

On the other hand, one thing that might be interesting is the new Raspberry Pi RP2040 Micropython port. There's a lot of fuss around that.  
Maybe someone would want to run Micropython+LVGL on that new MCU.

**Comment by amirgon** [comment]
@embeddedt I've just merged Micropython v1.14 and probably messed up the js and stm32 ports.
I've tested the unix and esp32 ports and they are good, I'm not sure what is causing the failures on js and stm32.  

Could you have a look?

**Comment by embeddedt** [comment]
STM32 is fixed; JS should be fixed shortly once it rebuilds.

**Comment by amirgon** [comment]
Great! Thanks @embeddedt !
All looks good, so I'm closing.
