### ISSUE TITLE
micropython lv_binding_micropython/examples/fb_test.py  #ImportError: no module named 'evdev'

### ISSUE THREAD

**Issue by china-zhangdj** [lvgl/lv_binding_micropython#119]
I compiled and installed lv_micropython on raspberrypi. When I executed "micropython lv_binding_micropython/examples/fb_test.py". I encountered an error: "ImportError: no module named'evdev'", but when I executed import evdev in the REPL, it did not Report an error, what caused this.

**Comment by amirgon** [comment]
Hi @china-zhangdj, 
`evdev` is a frozen module.
There is a Micropython bug related to `sys.path` affecting importing of frozen modules: https://github.com/micropython/micropython/issues/6419

To work around this, you can try running Micropython without command line arguments, and then something like this:

```python
import sys
sys.path.append('lib/lv_bindings/examples')
import fb_test
```

**Comment by china-zhangdj** [comment]
thank you wery much!

execute：
```python3
 import sys
sys.path.append("")
```
can fix it.

**Comment by amirgon** [comment]
Yes adding sys.path.append("") is a simpler workaround, thank you for this suggestion.

I'm closing this issue.
