### ISSUE TITLE
micropython v1.14 breaks mp_lodepng.c

### ISSUE THREAD

**Issue by uraich** [lvgl/lv_binding_micropython#121]
Hi Amir,
I saw that MicroPython V1.14 has been released and I gave it a try with lv_bindings. It turns out that mp_lodepng.c does not compile anymore. I added 
#include <stddef.h>
#include "py/mpconfig.h"
#include "py/misc.h"
which got rid of the problem. Now I have lv_micropython running with the underlying Micropython V1.14

**Comment by amirgon** [comment]
Hi @uraich,
Actually, I merged Micropython v1.14 today and didn't see this problem.
lv_micropython is now aligned to v1.14, and tested with unix/esp32 ports.
(stm32 and js ports still have some issues)
