### ISSUE TITLE
v8: Automatic casting

### ISSUE THREAD

**Issue by amirgon** [lvgl/lv_binding_micropython#135]
Use class information for automatic casting.  
When lv_obj is returned by a function or provided as parameter to a callback, it should be casted automatically to the actual object type as described by its class.

See https://github.com/lvgl/lvgl/issues/1763#issuecomment-801385901

**Comment by embeddedt** [comment]
Not stale.

(I have just removed the stale bot from this repository as it's just completely unreliable.)

**Comment by amirgon** [comment]
Done.
