### ISSUE TITLE
Improve CI tests

### ISSUE THREAD

**Issue by amirgon** [lvgl/lv_binding_micropython#151]
Currently [CI test](https://github.com/lvgl/lvgl/blob/master/.github/workflows/build_micropython.yml) builds and runs advanced_demo.py

- Need to make sure that if advanced_demo throws an exception, the test stops with an error. See: https://github.com/lvgl/lvgl/issues/1763#issuecomment-849874710
- It would make sense to run additional examples

**Comment by kisvegabor** [comment]
We can run all examples created by @uraich too.

**Comment by uraich** [comment]
I know that lv_example_style_14 still segfaults. I am looking into this

**Comment by amirgon** [comment]
> We can run all examples created by @uraich too.

Examples are part of LVGL repo now, right?
I think that first step would be to push the @uraich's examples into LVGL.

**Comment by kisvegabor** [comment]
> Examples are part of LVGL repo now, right?

Yes.

> I think that first step would be to push the @uraich's examples into LVGL.

I agree, adding minor changes later is easier.

**Comment by amirgon** [comment]
Done:
- Added `tests/run.sh` and `tests/run_test.py` that run all tests under `/examples` and send some events.
- Changed GitHub workflows of lvgl, lv_binding_micropython, lv_micropython to run `tests/run.sh`.
