### ISSUE TITLE
dynamic font loading example needs upgrade to V8

### ISSUE THREAD

**Issue by uraich** [lvgl/lv_binding_micropython#152]
I have done this and uploaded to 
https://github.com/uraich/lv_mpy_examples_v8/tree/main/lv_bindings
The fs_driver.py I use for V8 is in fs_driver_V8.py and must be re-named.
The additional fonts are in assets

**Comment by amirgon** [comment]
Could you open a PR?
Related: https://github.com/lvgl/lvgl/issues/2144#issuecomment-851956241

**Comment by amirgon** [comment]
Fixed by #153
