### ISSUE TITLE
build with esp32s2 failed

### ISSUE THREAD

**Issue by Meekdai** [lvgl/lv_binding_micropython#176]
I customized and compiled a board KM17 use esp32s2 chip.

```
make[3]: Entering directory '/opt/micropython/ports/esp32/build-km17'
[ 67%] Generating ../../lv_png.c.pp
[ 67%] Linking C static library libprotocomm.a
[ 67%] Generating ../../lv_espidf.c.pp
make[3]: Leaving directory '/opt/micropython/ports/esp32/build-km17'
/opt/micropython/lib/lv_bindings/driver/esp32/espidf.h:115:13: fatal error: esp32/clk.h: No such file or directory
 #   include "esp32/clk.h"
             ^~~~~~~~~~~~~
compilation terminated.
make[3]: Leaving directory '/opt/micropython/ports/esp32/build-km17'
make[3]: *** [esp-idf/main/CMakeFiles/__idf_main.dir/build.make:3392: lv_espidf.c.pp] Error 1
make[3]: *** Deleting file 'lv_espidf.c.pp'
make[2]: *** [CMakeFiles/Makefile2:4678: esp-idf/main/CMakeFiles/__idf_main.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```
I think `CONFIG_IDF_TARGET_ESP32S2`  in espidf.h:106 didn't work.
https://github.com/lvgl/lv_binding_micropython/blob/f5b509d6b543aa18060b03ce92604972f13f79b8/driver/esp32/espidf.h#L106

Here is my build log: https://github.com/Meekdai/lv_micropython-actions/runs/3539957254?check_suite_focus=true

**Comment by amirgon** [comment]
Currently only the esp32 is supported.  

If you (or anyone else) adds support for other flavors of the esp32 such as the esp32s2, you are welcome to open a PR.
