### ISSUE TITLE
Error when building the JS port locally

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_binding_micropython#190]
Hi,

I'm trying to build the JS port locally. I followed the steps from this action. All looks good except make -j8 -C ports/javascript` gives this error:

```shell
$  make -j8 -C ports/javascript
make: Entering directory '/home/kisvegabor/projects/littlevgl/edgeline/web/lv_micropython/ports/javascript'
************  lvgl_javascript version ************
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
Warning: FROZEN_DIR is deprecated in favour of FROZEN_MANIFEST
LVGL-GEN build/lvgl/lv_mpy.c
LODEPNG-GEN build/lodepng/mp_lodepng.c
error: invalid argument '-std=c++03' not allowed with 'C'
../../py/py.mk:44: recipe for target 'build/lvgl/lv_mpy.c' failed
make: *** [build/lvgl/lv_mpy.c] Error 1
make: *** Waiting for unfinished jobs....
error: invalid argument '-std=c++03' not allowed with 'C'
../../py/py.mk:69: recipe for target 'build/lodepng/mp_lodepng.c' failed
make: *** [build/lodepng/mp_lodepng.c] Error 1
make: Leaving directory '/home/kisvegabor/projects/littlevgl/edgeline/web/lv_micropython/ports/javascript'
```

Do you have any idea what could be wrong?

**Comment by kisvegabor** [comment]
I `grep`d for `std=c++03` in the whole `lv_micropython` project but I couldn't find any references either.

Both `echo $CXXFLAGS` and `echo $CFLAGS` returns nothing.

Maybe something is messed up on my machine but I tried to built the Eclipse SDL project with make and it worked. 

Interestingly the error shown for `lv_mpy.c` and `mp_lodepng.c` that are related to LVGL.

**Comment by embeddedt** [comment]
I will try 2.0.31 later and see if I can get the same error.
