### ISSUE TITLE
Support ESP32S3 IDF 4.4

### ISSUE THREAD

**Issue by Kevincoooool** [lvgl/lv_binding_micropython#197]
Hi，Can you support the newest esp32s3？

**Comment by amirgon** [comment]
Hi @Kevincoooool 
Which display driver are you planning to use?
It seems that esp-idf API is different between ESP32 and ESP32S3. So even if we support it, I'm not sure [existing display drivers](https://github.com/lvgl/lv_binding_micropython/blob/master/driver/esp32/ili9XXX.py) would work.

**Comment by Kevincoooool** [comment]
> Hi @Kevincoooool 
> Which display driver are you planning to use?
> It seems that esp-idf API is different between ESP32 and ESP32S3. So even if we support it, I'm not sure [existing display drivers](https://github.com/lvgl/lv_binding_micropython/blob/master/driver/esp32/ili9XXX.py) would work.

Hello, I've seen that the original warehouse of micropython already supports esp32s3. For the API part, just set DMA to auto during SPI initialization. Others are compatible. Can you merge the lvgl part in the master branch of the original warehouse? Thank you

**Comment by amirgon** [comment]
Related discussion on https://github.com/lvgl/lv_binding_micropython/issues/208
Let's continue the discussion there.
