### ISSUE TITLE
build ports/rp2 miss lvgl_interface

### ISSUE THREAD

**Issue by xinshuwei** [lvgl/lv_binding_micropython#207]
chris@LAPTOP-661KN90D:~/lv_micropython/ports/rp2$ make USER_C_MODULES=../../lv_bindings/bindings.cmake
[ -d build-PICO ] || cmake -S . -B build-PICO -DPICO_BUILD_DOCS=0 -DMICROPY_BOARD=PICO -DUSER_C_MODULES=../../lv_bindings/bindings.cmake
PICO_SDK_PATH is /home/chris/lv_micropython/lib/pico-sdk
Defaulting PICO_PLATFORM to rp2040 since not specified.
Defaulting PICO platform compiler to pico_arm_gcc since not specified.
PICO compiler is pico_arm_gcc
PICO_GCC_TRIPLE defaulted to arm-none-eabi
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/arm-none-eabi-gcc
PICO target board is pico.
Using board configuration from /home/chris/lv_micropython/lib/pico-sdk/src/boards/include/boards/pico.h
-- Found Python3: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter
TinyUSB available at /home/chris/lv_micropython/lib/tinyusb/src/portable/raspberrypi/rp2040; adding USB support.
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.17") found components: doxygen dot
Including User C Module(s) from ../../lv_bindings/bindings.cmake
CMake Error at /home/chris/lv_micropython/py/usermod.cmake:9 (get_target_property):
  get_target_property() called with non-existent target "lvgl_interface".
Call Stack (most recent call first):
  /home/chris/lv_micropython/py/usermod.cmake:24 (usermod_gather_sources)
  /home/chris/lv_micropython/py/usermod.cmake:24 (usermod_gather_sources)
  /home/chris/lv_micropython/py/usermod.cmake:47 (usermod_gather_sources)
  CMakeLists.txt:54 (include)

**CMake Error at /home/chris/lv_micropython/py/usermod.cmake:15 (get_target_property):**
  get_target_property() called with non-existent target "lvgl_interface".
Call Stack (most recent call first):
  /home/chris/lv_micropython/py/usermod.cmake:24 (usermod_gather_sources)
  /home/chris/lv_micropython/py/usermod.cmake:24 (usermod_gather_sources)
  /home/chris/lv_micropython/py/usermod.cmake:47 (usermod_gather_sources)
  CMakeLists.txt:54 (include)

**CMake Error at /home/chris/lv_micropython/py/usermod.cmake:21 (get_target_property):**
  get_target_property() called with non-existent target "lvgl_interface".
Call Stack (most recent call first):
  /home/chris/lv_micropython/py/usermod.cmake:24 (usermod_gather_sources)
  /home/chris/lv_micropython/py/usermod.cmake:24 (usermod_gather_sources)
  /home/chris/lv_micropython/py/usermod.cmake:47 (usermod_gather_sources)
  CMakeLists.txt:54 (include)

Found User C Module(s): usermod_lv_bindings, lvgl_interface
ELF2UF2 will need to be built
-- Configuring incomplete, errors occurred!

how to fix this, please help me

**Comment by amirgon** [comment]
> how to fix this, please help me

Please send questions to the forum: https://forum.lvgl.io/c/micropython/8

The rp2 port is built regularly in the CI, so simply follow the build step there: https://github.com/lvgl/lv_micropython/blob/master/.github/workflows/rp2_port.yml
