### ISSUE TITLE
Display driver can't be compiled  into the firmware

### ISSUE THREAD

**Issue by ARIYAWOW** [lvgl/lv_binding_micropython#214]
I've  used `BOARD=STM32F405RGT6 USER_C_MODULES=../../lib/lv_bindings/driver/STM32F405RGT6` to build my stm32 firmware, but the display driver not compiled into the firmware, I find it be generated in 'ports' folder, maybe I miss some  step, can u help me?

**Comment by amirgon** [comment]
> BOARD=STM32F405RGT6 USER_C_MODULES=../../lib/lv_bindings/driver/STM32F405RGT6

Currently we only support STM32F7DISC.
See https://github.com/lvgl/lv_binding_micropython/issues/212
Contribution of new boards/display drivers are welcome!

CC @embeddedt
