### ISSUE TITLE
st77xx.py lv.COLOR.DEPTH incorrect name

### ISSUE THREAD

**Issue by ngc6589** [lvgl/lv_binding_micropython#229]
I tried generic-st77xx-with-xpt2046.py demo to try lvgl micropython on my Raspberry Pi Pico (RP2040), but it did not work.

In lib/lv_bindings/driver/generic/st77xx.py

 if lv.COLOR.DEPTH!=16: raise RuntimeError(f'LVGL *must* be compiled with LV_COLOR_DEPTH=16 (currently LV_COLOR_DEPTH={lv.COLOR.DEPTH}.')

I looked at REPL >>>help(lv) and found that
  SIZE_CONTENT -- 10193
  COLOR_DEPTH -- 16
  IMG_ZOOM_NONE -- 256
  RADIUS_CIRCLE -- 32767

COLOR_DEPTH seems to have been changed from COLOR.DEPTH to COLOR_DEPTH.
It appears that the variable name correction in the demo program was omitted.

Thank you in advance.

**Comment by amirgon** [comment]
Thank you for reporting this!

Fixed.
