### ISSUE TITLE
Set background color

### ISSUE THREAD

**Issue by projetoarduino** [lvgl/lv_binding_micropython#230]
hello, guys, I looked in several places and didn't find something simple like setting the background color of my lcd

Sorry for the question, but I really looked for this information and couldn't find it.

Is there any documentation, complete about lvgl in micropython

**Comment by embeddedt** [comment]
[Here](https://sim.lvgl.io/v8.3/micropython/ports/javascript/index.html?script_direct=4c7a5a9dc3de943c98f10d90be95dd9b00de2ee0) is an example for the online simulator.

**Comment by amirgon** [comment]
Thanks @embeddedt for the example.

@projetoarduino Please use the [LVGL forum](https://forum.lvgl.io/c/micropython/8) for questions.

Closing.
