### ISSUE TITLE
is it lv.SIZE_CONTENT or lv.SIZE.CONTENT ?

### ISSUE THREAD

**Issue by BrianPugh** [lvgl/lv_binding_micropython#239]
In python code generated by SquareLine Studio v1.1.1, `lv.SIZE.CONTENT` is regularly reference. However, in my latest lvgl-micropython build, it's `lv.SIZE_CONTENT`. Which is correct?

**Comment by embeddedt** [comment]
Some names were adjusted in the v9 bindings to fix a [bug](https://github.com/lvgl/lv_binding_micropython/issues/199). However, I think SquareLine still uses v8 names.

**Comment by BrianPugh** [comment]
thanks! I can manually adjust the exported code for now; I'm assuming SquareLine Studio will be updated once an official v9 is released.
