### ISSUE TITLE
unable to use latest micropython due to MP_DEFINE_CONST_OBJ_TYPE replaces mp_obj_type_t

### ISSUE THREAD

**Issue by meetroger** [lvgl/lv_binding_micropython#244]
since the latest micropython makes all mp_obj_type_t defs use `MP_DEFINE_CONST_OBJ_TYPE` (https://github.com/micropython/micropython/commit/662b9761b37b054f08fe2f7c00d0fce3a418d0b0), the gen_mpy.py must be modified to use MP_DEFINE_CONST_OBJ_TYPE. The `mp_lv_obj_types` is assumed to use items with a fixed length, which make it hard to migrate.

**Comment by amirgon** [comment]
[lv_micropython](https://github.com/lvgl/lv_micropython) and lv_binding_micropython follow the official Micropython **releases**.  
Latest Micropython release as of today is [v1.19.1](https://github.com/micropython/micropython/releases/tag/v1.19.1) and lv_micropython/lv_binding_micropython are compatible with it.

When a new Micropython version is released, I'll adap lv_micropython and lv_binding_micropython to it.  
In the meanwhile, you can try using the changes in https://github.com/lvgl/lv_binding_micropython/pull/242 which include the `MP_DEFINE_CONST_OBJ_TYPE` modification.
