### ISSUE TITLE
Just a compiler warning

### ISSUE THREAD

**Issue by kdschlosser** [lvgl/lv_binding_micropython#257]
When compiling for an ESP32 the following warning comes up.

```
/lv_micropython/lib/lv_bindings/lvgl/src/misc/lv_timer.c: In function 'lv_timer_exec':
/lv_micropython/lib/lv_bindings/lvgl/src/misc/lv_timer.c:316:52: warning: suggest braces around empty body in an 'else' statement [-Wempty-body]
         else TIMER_TRACE("timer callback finished");
```

**Comment by amirgon** [comment]
This is related to LVGL sources not to the binding.  
Could you please re-open this on [LVGL repo](https://github.com/lvgl/lvgl/issues/new/choose)? 
(I think it's better to open a PR instead of an issue in this case)
