### ISSUE TITLE
event_loop not working on raspberry pi (armv7)

### ISSUE THREAD

**Issue by daviel** [lvgl/lv_binding_micropython#273]
I found a really weird behavior with the current master branch and raspberry pi. When starting the event loop with the call
```event_loop = event_loop()``` you get an error code 22 (invalid argument). 

```
  File "lv_utils.py", line 95, in __init__
  File "lv_timer.py", line 142, in init
  File "lv_timer.py", line 103, in timer_create
RuntimeError: timer_create_ error: -1 (errno = 22)
```

I took a look at the code and found the problem lies in the lv_timer.py implementation ([SIGRTMIN = __libc_current_sigrtmin()](https://github.com/lvgl/lv_binding_micropython/blob/e4cc7668cd6ed170d71c874ab2ba15cc8804fd4a/driver/linux/lv_timer.py#LL64C12-L64C12)). The value comes from the C-call __libc_current_sigrtmin (returns 34 on raspberry pi). When I change this value to 1 everything works as expected. The sigrtmax value is 64 btw. 

On a x86-64 debian system I did not encounter this error. I think 34 should be the expected value here as the documentation from [RT-Signals](https://www.man7.org/linux/man-pages/man7/signal.7.html) says the same. 

I have built the native [example](https://man7.org/linux/man-pages/man2/timer_create.2.html) from librt also and it is using also the sigrtmin value of 34 but in this case working as expected.

Any idea what exactly the problem is here?

**Comment by amirgon** [comment]
> The value comes from the C-call __libc_current_sigrtmin (returns 34 on raspberry pi). When I change this value to 1 everything works as expected.

Maybe 34 is taken by some RP service? Could you try some other values? (35,36,etc.)
One possibility is to re-try signals up to sigrtmax when getting an error.
A simpler option is to handle RP differently on lv_utils.py and set `default_timer_id`. Today we set it differently for pyboard and rp2. Try to set it to 1 or 2 for example.

https://github.com/lvgl/lv_binding_micropython/blob/e4cc7668cd6ed170d71c874ab2ba15cc8804fd4a/lib/lv_utils.py#L49-L56

> I have built the native [example](https://man7.org/linux/man-pages/man2/timer_create.2.html) from librt also and it is using also the sigrtmin value of 34 but in this case working as expected.

So you are saying timer 34 still works in some cases? Maybe Micropython itself reserves timer 34, so it's not available when running under Micropython.  
btw does `SIGRTMIN` on your C code has the same value as `__libc_current_sigrtmin()` (both 34?)

**Comment by daviel** [comment]
Yes this is what gets printed out in the c example:
```
Establishing handler for signal 34
Blocking signal 34
timer ID is 0xf6c598
Sleeping for 1 seconds
Unblocking signal 34
Caught signal 34
    sival_ptr = 0x7ef0958c;     *sival_ptr = 0xf6c598
    overrun count = 50022060
min signal __libc_current_sigrtmin: 34
```

I can run the c-program without problems even if MicroPython is running so MicroPython itself does not seem to block the signal.

**Comment by daviel** [comment]
Okay I think I found the problem. 

The struct in the lv_timer is expecting a 64 bit system:

```
sigevent_t = {
    "sigev_value": (0, sigval_t),
    "sigev_signo": 8 | uctypes.INT32,
    "sigev_notify": 12 | uctypes.INT32,
}
```

The offset a sigev_signo is set to 8 but should be 4 on a 32 bit system. I will create a pull request to get it fixed.

**Comment by amirgon** [comment]
> Okay I think I found the problem.
> 
> The struct in the lv_timer is expecting a 64 bit system:

This is great! Thank you.
Indeed, pointer size is architecture dependent. I've merged your PR.
