### ISSUE TITLE
Generating ../../frozen_content.c   error 

### ISSUE THREAD

**Issue by ivrrtts629** [lvgl/lv_binding_micropython#275]
I get this error when I build  lv_micropython for esp32s3 n32r8v , can someone tell me why, thanks!
[1215/1646] Generating ../../frozen_content.c
FAILED: frozen_content.c /pro/lv_micropython/ports/esp32/build-GENERIC_S3_SPIRAM_OCT/frozen_content.c
cd /pro/lv_micropython/ports/esp32/build-GENERIC_S3_SPIRAM_OCT/esp-idf/main && /opt/esp/python_env/idf4.4_py3.8_env/bin/python3.8 /pro/lv_micropython/tools/makemanifest.py -o /pro/lv_micropython/ports/esp32/build-GENERIC_S3_SPIRAM_OCT/frozen_content.c -v MPY_DIR=/pro/lv_micropython -v MPY_LIB_DIR=/pro/lv_micropython/../micropython-lib -v PORT_DIR=/pro/lv_micropython/ports/esp32 -v BOARD_DIR=/pro/lv_micropython/ports/esp32/boards/GENERIC_S3_SPIRAM_OCT -b /pro/lv_micropython/ports/esp32/build-GENERIC_S3_SPIRAM_OCT -f-march=xtensawin /pro/lv_micropython/ports/esp32/boards/manifest.py
Traceback (most recent call last):
  File "/pro/lv_micropython/ports/esp32/modules/display_driver_utils.py", line 1
SyntaxError: invalid syntax

**Comment by amirgon** [comment]
esp32s3 is not formally supported yet on lv_micropython.
See https://github.com/lvgl/lv_binding_micropython/issues/227

**Comment by ivrrtts629** [comment]
thanks!
