### ISSUE TITLE
Linemeter style changes in v7

### ISSUE THREAD

**Issue by kdunn926** [lvgl/lv_binding_micropython#87]
I want to begin by saying thank you all for this incredibly powerful tool. I'd never have guessed prototyping a UI for an embedded device could be possible in such short iteration cycles.

I was previously using a build from master (unhelpfully vague, I realize) and recently pulled down lv_micropython:release/v7 and subsequently ran `git submodule update`. There seems to be various API changes (I'll happily produce docs fixes), along with some functional changes. For example, now when I create a linemeter it looks like this (ignore label):
![Screen Shot 2020-07-08 at 4 02 04 PM](https://user-images.githubusercontent.com/7925800/86975306-4c8da480-c135-11ea-8559-cb6182870f31.png)

It used to (should?) look like this:
![Screen Shot 2020-07-08 at 4 02 15 PM](https://user-images.githubusercontent.com/7925800/86975319-53b4b280-c135-11ea-9473-16bc0c0b0469.png)

I'm happy to poke around a determine the issue myself but any clues on where to start would be appreciated.

Thanks!

**Comment by amirgon** [comment]
Hi @kdunn926 !
Indeed API changed between v6 and v7. Major releases usually contain some API changes.
This question is unrelated to Micropython, the same change would appear on C code that uses LVGL.

We are using GitHub issues mainly to report bugs, for question we have a forum: https://forum.lvgl.io.
**Please post this question on the forum**. Probably the "how-to" category would be appropriate.

**Comment by kdunn926** [comment]
Thanks for the helpful suggestion @amirgon . For posterity, I've created a forum topic here: https://forum.lvgl.io/t/line-meter-material-style-broken-in-v7/2687
