### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by amirgon** [lvgl/lv_binding_micropython#9]
Integrate Continues Integration to make sure littlevgl/lv_micropython is building with no errors.
Probably will try Travis.
Related: littlevgl/lvgl#768

**Comment by kisvegabor** [comment]
I've "pinned" this issue to be not closed automatically.

**Comment by amirgon** [comment]
Added GitHub action to build lv_micropython upon push/pull.
Also added an action to lv_bindings_micropython.

https://github.com/lvgl/lv_binding_micropython/commit/caeb6479e70d2af10afcf0e0335cbd751f8a9819
https://github.com/lvgl/lv_micropython/commit/5429b976d3659969d54d7271e9bd4e816c0448c5
